apiVersion: v1
kind: ReplicationController
metadata:
  name: alertmanager-rc
spec:
  replicas: 1
  selector:
    app: alertmanager
  template:
    metadata:
      name: alertmanager
      labels:
        app: alertmanager
    spec:
      hostNetwork: true
      nodeSelector:
        monitoring: telemetry
      containers:
      - name: alertmanager
        image: prom/alertmanager
        ports:
        - containerPort: 9093
          hostPort: 9093
