apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter-ds
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app: node-exporter
    spec:
      hostNetwork: true
      containers:
      - name: node-exporter
        image: prom/node-exporter
        args: []
        ports:
        - containerPort: 9100
          hostPort: 9100
