kind: PersistentVolume
apiVersion: v1
metadata:
  name: telemetry-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/docker/containers/telemetry"

